### ISSUE TITLE
List<GetConnectedAndPairedBluetoothDevicesModel>

### ISSUE THREAD

**Issue by bhapps** [sirvar/bluetoothkit-android#2]
Hi Sirvar,

Is or would something like this be implemented?
Would be great to get a list of current connected/paired devices (to do some validations & authentications (serverside))

** Any advice on below **
fun getPairedDevices(): Set<BluetoothDevice> {
        return bluetoothAdapter.bondedDevices
}

**Comment by sirvar** [comment]
@Bennith Would you please elaborate? That method is implemented. Check it out in the docs [here](https://sirvar.github.io/bluetoothkit-android/com.sirvar.bluetoothkit/-bluetooth-kit/get-paired-devices.html)

**Comment by bhapps** [comment]
We can close this as you have this already implemented;
Thanks.
