### ISSUE TITLE
Type Mismatch

### ISSUE THREAD

**Issue by jakemurray04** [sirvar/bluetoothkit-android#4]
Error

val device = bluetoothKit.getDeviceByName("HC-06")
bluetoothKit.connect(device)

Type Mismatch.
Required: BluetoothDevice
Found: BluetoothDevice?

**Comment by jakemurray04** [comment]
Solved it by doing:

var device = bluetoothKit.getDeviceByName("HC-06") as BluetoothDevice

Won't close for devs to take notice and take action.

**Comment by sirvar** [comment]
@jakemurray04 currently looking into this

**Comment by aouerf** [comment]
This is intended behavior. If the device is not found, it will return null.
